### PR TITLE
Add Firebase to app

### LINKED ISSUE #46: Add Firebase to Android Application
**Description:** 
Connect the Firebase project to the Android application

### PR DESCRIPTION
**Pull request by WJXHenry**
Closes #46 

**Summary**
Connects Firebase to the Android application.

I wasn't comfortable with committing the Firebase API key to GitHub, so I left instructions in the README on setting up Firebase for the app. I downloaded the [`google-services.json`](https://drive.google.com/file/d/11CGUTE2teLygTExGXli6GSmecYrLQqS6/) file into my Google Drive and linked it in the README for easier access to the file. The file should be shared with everyone in the group (UAlberta email).

### CODE REVIEW

**Comment by bojotamara** [comment]
@WJXHenry Can the TA access the file to run it?

**Comment by WJXHenry** [comment]
@bojotamara Currently, no. We can add him to the list of people who has access to it. I'll ask him if he prefers the file to be in GitHub instead.

**Comment by bojotamara** [comment]
@WJXHenry Kk, I don't mind it being in GitHub personally, because in real life no one would have access to the source code repo. They would just download the APK file. This is public just for TAs/instructors to use

**Comment by darrentran** [comment]
Merging in so that we can start working on other issues. Will create another ticket to decide whether we want to include `google-services .json`.

**Review by darrentran — APPROVED** [review]
Approving so we can start working on other issues

**Pull request merged**
