### PR TITLE
Logout on back pressed

### LINKED ISSUE #114: Fix: Logout on back button pressed in mood history fragment
**Description:** 
Pressing the back button navigates the user to the login screen but does not actually log them out.

**Rationale:** 
So that I am not confused that I'm still logged in even though I pressed the back button and was taken back to the login screen.

### PR DESCRIPTION
**Pull request by WJXHenry**
Closes #114 

**Summary**
- Logs the user out when the back button is pressed
- Added a confirmation `Toast` before logging out (user has to press back twice)

### CODE REVIEW

**Comment by bojotamara** [comment]
I'm not the biggest fan of logging out at all when pressing back. (Even if we confirm it with the user) Most apps just return to the home screen.

**Comment by WJXHenry** [comment]
@bojotamara This implementation only logs the user out when they are on the mood history screen. The back presses on the other fragments/activities still have the same functionality.

**Comment by bojotamara** [comment]
@WJXHenry By home screen, I meant like exit the app but don't log out. Pressing back on most apps just exits the app

**Comment by WJXHenry** [comment]
@bojotamara Oh I see what you mean now. I'll change it to have the back button exit the app without logging out in the mood history fragment

**Review by bojotamara — APPROVED** [review]

**Pull request merged**
